[tool.poetry]
name = "sensing-garden-api-test"
version = "0.1.0"
description = "API Test for Sensing Garden Backend"
authors = ["Sensing Garden Team"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.0"
boto3 = "^1.24.0"
python-dotenv = "^0.20.0"
pillow = "^9.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
